<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Fotografi</name>
   <tag></tag>
   <elementGuidId>1c2c2a61-c2d5-4be6-b88f-86cc13f75e69</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[3]/div/div/div/div/div/div/div[2]/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.F6l.Uex.XBe.k1A.zI7.iyn.Hsu > div.Pj7.sLG.XiG.ho-.m1e > div.FNs.XiG.ho-.zI7.iyn.Hsu > div.CCY.S9z.eEj.oCZ.Tbt.L4E.e8F.BG7 > div.JME.MIw.Rym.VxL.hjj.ojN.p6V.wc1.zI7.iyn.Hsu > div.tBJ.dyH.iFc.sAJ.xnr.zDA.IZT.H2s</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>06d304b5-a172-4f60-8065-374f2c98c940</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>tBJ dyH iFc sAJ xnr zDA IZT H2s</value>
      <webElementGuid>4e278f11-6d2d-4b3e-b353-e3303a161afb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Fotografi</value>
      <webElementGuid>e71295b2-a6d5-4deb-bace-cccbc252290c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;id&quot;]/body[1]/div[@class=&quot;NIm MIw QLY Rym&quot;]/div[1]/div[1]/div[@class=&quot;Fwt _he Hsu _O1 mQ8 Rym QLY KS5 L4E&quot;]/div[@class=&quot;ZHw XiG XbT _O1 SpV ho- rDA jar CCY&quot;]/div[@class=&quot;Jea XiG jzS ujU zI7 iyn Hsu&quot;]/div[@class=&quot;XbT XiG lnZ ujU wsz zI7 iyn Hsu&quot;]/div[@class=&quot;Jea XiG jzS zI7 iyn Hsu&quot;]/div[@class=&quot;ujU zI7 iyn Hsu&quot;]/div[@class=&quot;jzS un8 C9i TB_&quot;]/div[@class=&quot;Cii ujU wYR zI7 iyn Hsu&quot;]/div[@class=&quot;Jea XBe iD5 kzZ zI7 iyn Hsu&quot;]/div[@class=&quot;C9q Shl zI7 iyn Hsu&quot;]/div[@class=&quot;Jea KS5 LJB Pw5 XgI ho- mQ8 urM zI7 iyn Hsu&quot;]/div[@class=&quot;sLG zI7 iyn Hsu&quot;]/div[@class=&quot;F6l Uex XBe k1A zI7 iyn Hsu&quot;]/div[@class=&quot;Pj7 sLG XiG ho- m1e&quot;]/div[@class=&quot;FNs XiG ho- zI7 iyn Hsu&quot;]/div[@class=&quot;CCY S9z eEj oCZ Tbt L4E e8F BG7&quot;]/div[@class=&quot;JME MIw Rym VxL hjj ojN p6V wc1 zI7 iyn Hsu&quot;]/div[@class=&quot;tBJ dyH iFc sAJ xnr zDA IZT H2s&quot;]</value>
      <webElementGuid>013db5e1-a48d-4268-b205-6d63c841f40f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div/div/div/div/div[2]/div</value>
      <webElementGuid>cf9b76f5-46dc-44b3-b229-a3fb4707fb4a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Fotografi' or . = 'Fotografi')]</value>
      <webElementGuid>d6472a1e-985f-480f-9c34-2b39b5b58432</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
