<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Next</name>
   <tag></tag>
   <elementGuidId>f7ee6ab6-8ce3-4325-ae5b-281515feb0a4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[2]/button/div/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.RCK.Hsu.USg.adn.CCY.gn8.L4E.kVc.S9z.F10.xD4.fZz.hUC.Il7.Jrn.hNT.BG7.hDj._O1.KS5.mQ8.Tbt.L4E > div.tBJ.dyH.iFc.sAJ.xnr.tg7.H2s</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>12689da1-3145-4cc7-bd4f-5cb8a8adc458</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>tBJ dyH iFc sAJ xnr tg7 H2s</value>
      <webElementGuid>94d1ab39-1a7d-468c-bd59-31ae6e077de7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Next</value>
      <webElementGuid>2c5a4e92-2d4a-4d92-b752-c886380bb38a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;en&quot;]/body[1]/div[@class=&quot;NIm MIw QLY Rym&quot;]/div[1]/div[1]/div[@class=&quot;Fwt _he Hsu _O1 mQ8 Rym QLY KS5 L4E&quot;]/div[@class=&quot;ZHw XiG XbT _O1 SpV ho- rDA jar CCY&quot;]/div[@class=&quot;Jea XiG jzS ujU zI7 iyn Hsu&quot;]/div[@class=&quot;XbT XiG lnZ ujU wsz zI7 iyn Hsu&quot;]/div[@class=&quot;Jea XiG jzS zI7 iyn Hsu&quot;]/div[@class=&quot;ujU zI7 iyn Hsu&quot;]/div[@class=&quot;Jea LCN Lej jzS zI7 iyn Hsu&quot;]/div[@class=&quot;CDp zI7 iyn Hsu&quot;]/button[@class=&quot;RCK Hsu USg adn CCY gn8 L4E kVc oRi lnZ wsz YbY&quot;]/div[@class=&quot;RCK Hsu USg adn CCY gn8 L4E kVc S9z F10 xD4 fZz hUC Il7 Jrn hNT BG7 hDj _O1 KS5 mQ8 Tbt L4E&quot;]/div[@class=&quot;tBJ dyH iFc sAJ xnr tg7 H2s&quot;]</value>
      <webElementGuid>fdd975d2-13fd-4f18-94eb-777e8d5e80e3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/button/div/div</value>
      <webElementGuid>246738ac-5ba4-402f-9b4f-4041ef860c5d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Next' or . = 'Next')]</value>
      <webElementGuid>8dbc808e-466e-41c1-a2f3-0781d50818c7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
