<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Selesai</name>
   <tag></tag>
   <elementGuidId>7e78981f-288c-44ad-b717-de8ff9c42b30</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[2]/button/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.KS5.hs0.mQ8.un8.tkf.TB_</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>f15b53d4-bc3a-4c07-b48c-8a04021117f0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>KS5 hs0 mQ8 un8 tkf TB_</value>
      <webElementGuid>df5735c6-f14b-48e7-83a8-694a13297866</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Selesai</value>
      <webElementGuid>c10f0a4a-81b3-444a-b07b-7c0638cd5413</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;id&quot;]/body[1]/div[@class=&quot;NIm MIw QLY Rym&quot;]/div[1]/div[1]/div[@class=&quot;Fwt _he Hsu _O1 mQ8 Rym QLY KS5 L4E&quot;]/div[@class=&quot;ZHw XiG XbT _O1 SpV ho- rDA jar CCY&quot;]/div[@class=&quot;Jea XiG jzS ujU zI7 iyn Hsu&quot;]/div[@class=&quot;XbT XiG lnZ ujU wsz zI7 iyn Hsu&quot;]/div[@class=&quot;Jea XiG jzS zI7 iyn Hsu&quot;]/div[@class=&quot;ujU zI7 iyn Hsu&quot;]/div[@class=&quot;zI7 iyn Hsu&quot;]/div[@class=&quot;ALa LCN Lej XiG zI7 iyn Hsu&quot;]/button[@class=&quot;RCK Hsu USg adn CCY gn8 L4E kVc S9z F10 xD4 fZz hUC Il7 Jrn hNT BG7&quot;]/div[@class=&quot;KS5 hs0 mQ8 un8 tkf TB_&quot;]</value>
      <webElementGuid>af8e616a-4abf-41f0-bba5-67b1301a91c7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/button/div</value>
      <webElementGuid>6b6a3bf7-7bb9-47a2-a783-bd55885f3b21</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Selesai' or . = 'Selesai')]</value>
      <webElementGuid>421a8013-81b5-4688-b398-4004cab86adb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
