<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Berikutnya</name>
   <tag></tag>
   <elementGuidId>91cdc520-f8aa-46a1-9a85-97e763cdd341</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[2]/button/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.KS5.hs0.mQ8.un8.tkf.TB_</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>c76292e2-dcea-4cc3-8fe7-417c777c44d0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>KS5 hs0 mQ8 un8 tkf TB_</value>
      <webElementGuid>857ab7c9-3ac8-42a0-8a3b-eefeb89c91a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Berikutnya</value>
      <webElementGuid>f0653704-4358-4df2-a3ce-fc90f0c09339</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;id&quot;]/body[1]/div[@class=&quot;NIm MIw QLY Rym&quot;]/div[1]/div[1]/div[@class=&quot;Fwt _he Hsu _O1 mQ8 Rym QLY KS5 L4E&quot;]/div[@class=&quot;ZHw XiG XbT _O1 SpV ho- rDA jar CCY&quot;]/div[@class=&quot;Jea XiG jzS ujU zI7 iyn Hsu&quot;]/div[@class=&quot;XbT XiG lnZ ujU wsz zI7 iyn Hsu&quot;]/div[@class=&quot;Jea XiG jzS zI7 iyn Hsu&quot;]/div[@class=&quot;ujU zI7 iyn Hsu&quot;]/div[@class=&quot;Jea LCN Lej jzS zI7 iyn Hsu&quot;]/div[@class=&quot;Uex ojN zI7 iyn Hsu&quot;]/button[@class=&quot;RCK Hsu USg adn CCY gn8 L4E kVc S9z F10 xD4 fZz hUC Il7 Jrn hNT BG7&quot;]/div[@class=&quot;KS5 hs0 mQ8 un8 tkf TB_&quot;]</value>
      <webElementGuid>ab7f6f35-3ce8-4dd0-b726-228105d726ae</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/button/div</value>
      <webElementGuid>1f28c94d-01e3-4053-9d94-d10462722a3f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Berikutnya' or . = 'Berikutnya')]</value>
      <webElementGuid>b15fdc90-eb82-439d-abb5-ad0b3fffb4b5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
