<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Continue</name>
   <tag></tag>
   <elementGuidId>b18dccf2-9a36-43c4-8dce-46a8f6ac9c9b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__PWS_ROOT__']/div/div/div[2]/div/div/div/div/div/div[5]/div/div/form/div[8]/button/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button.red.SignupButton.active > div.zI7.iyn.Hsu</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>3037b4a1-f241-465a-9a8e-6811333f6766</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>zI7 iyn Hsu</value>
      <webElementGuid>b76e6728-3e3f-4fe0-b18e-307aefce0a51</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Continue</value>
      <webElementGuid>553659d4-3f3f-4cae-9e0c-e145b4e4075a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__PWS_ROOT__&quot;)/div[1]/div[1]/div[@class=&quot;zI7 iyn Hsu&quot;]/div[@class=&quot;QLY Rym ZZS _he ojN p6V zI7 iyn Hsu&quot;]/div[1]/div[1]/div[@class=&quot;zI7 iyn Hsu&quot;]/div[@class=&quot;zI7 iyn Hsu&quot;]/div[@class=&quot;XiG zI7 iyn Hsu&quot;]/div[@class=&quot;zI7 iyn Hsu&quot;]/div[@class=&quot;zI7 iyn Hsu&quot;]/form[1]/div[@class=&quot;zI7 iyn Hsu&quot;]/button[@class=&quot;red SignupButton active&quot;]/div[@class=&quot;zI7 iyn Hsu&quot;]</value>
      <webElementGuid>934ba946-128c-4f7a-84b8-cb223c6a9404</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__PWS_ROOT__']/div/div/div[2]/div/div/div/div/div/div[5]/div/div/form/div[8]/button/div</value>
      <webElementGuid>ef0a18ca-eac7-47cc-be16-1d69cfcc6567</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[8]/button/div</value>
      <webElementGuid>74d546f2-f6b5-46fb-b628-ac0eb473d61c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Continue' or . = 'Continue')]</value>
      <webElementGuid>5b074ebf-ec37-48d4-9314-70bdcc8d0013</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
