<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframegsi_857137_326115</name>
   <tag></tag>
   <elementGuidId>367d819b-ed00-4a85-8087-cb7648d672a1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@id='gsi_857137_326115']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#gsi_857137_326115</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>b3bae621-cf51-45ea-80c2-0ec35281c977</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://accounts.google.com/gsi/button?size=large&amp;shape=pill&amp;text=continue_with&amp;theme=outline&amp;width=268px&amp;logo_alignment=left&amp;click_listener=()%3D%3E(0%2Ci.EX)(%7Bevent%3A%22start%22%2Cprovider%3A%22google%22%7D)&amp;client_id=694505692171-31closf3bcmlt59aeulg2j81ej68j6hk.apps.googleusercontent.com&amp;iframe_id=gsi_857137_326115&amp;as=YMwKzFnUfPAu+J5LYZsyhA&amp;hl=en-US</value>
      <webElementGuid>e2a21c4b-b79d-4ff9-af66-4478921b4c94</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>gsi_857137_326115</value>
      <webElementGuid>e97affca-5eb2-47ac-90ee-0cdaaa7ffe99</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Sign in with Google Button</value>
      <webElementGuid>b3fcc903-67ff-473e-825d-3b0b1ee4d605</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;gsi_857137_326115&quot;)</value>
      <webElementGuid>9974b9f9-0f45-4d5d-a2a5-4a08c66db4f3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@id='gsi_857137_326115']</value>
      <webElementGuid>9564ab38-2dbd-47fd-a7e2-6e84bae00157</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__PWS_ROOT__']/div/div/div[2]/div/div/div/div/div/div[4]/div/div[3]/div/div/div/iframe</value>
      <webElementGuid>08d52d7e-e4b2-48ba-af58-0ee8cce89761</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/iframe</value>
      <webElementGuid>cc600724-f5d7-422c-b3c1-dbee220c6b93</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@src = 'https://accounts.google.com/gsi/button?size=large&amp;shape=pill&amp;text=continue_with&amp;theme=outline&amp;width=268px&amp;logo_alignment=left&amp;click_listener=()%3D%3E(0%2Ci.EX)(%7Bevent%3A%22start%22%2Cprovider%3A%22google%22%7D)&amp;client_id=694505692171-31closf3bcmlt59aeulg2j81ej68j6hk.apps.googleusercontent.com&amp;iframe_id=gsi_857137_326115&amp;as=YMwKzFnUfPAu+J5LYZsyhA&amp;hl=en-US' and @id = 'gsi_857137_326115' and @title = 'Sign in with Google Button']</value>
      <webElementGuid>addf1c2c-4c38-4c8f-9ca0-648e23f5d44c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
