<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_genderOptions</name>
   <tag></tag>
   <elementGuidId>6748fb4a-1b22-411e-b265-df19f0d31dec</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='female']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#female</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>4ab587a4-9934-4cc5-a9ca-99f58c6118b7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>M8E MIw e43 xpn ac9 BG7</value>
      <webElementGuid>89eaa20b-7629-4196-8b5a-302b5d633969</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>female</value>
      <webElementGuid>e18d1173-bbee-4826-8dc5-f8296890897e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>genderOptions</value>
      <webElementGuid>e153a109-7c4e-41a4-ae76-b95b0d3f75c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>bb96b510-52bd-489b-8cd3-896fcb860ea4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>female</value>
      <webElementGuid>d6079164-df1e-4c7e-ab0e-ddcad259f3e6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;female&quot;)</value>
      <webElementGuid>762aa628-1ee4-41e9-ac03-7e9ef1398648</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='female']</value>
      <webElementGuid>ed8db26c-29e9-4f3a-94da-e592ef4d984c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//label/div/div/div/div/input</value>
      <webElementGuid>bb3353b0-e10c-4682-9d2c-2f17db00149a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'female' and @name = 'genderOptions' and @type = 'radio']</value>
      <webElementGuid>f6245a22-725a-4d7b-99b0-4a9c086defc5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
