<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_AfrikaansBahasa IndonesiaBahasa Mala_7c313a</name>
   <tag></tag>
   <elementGuidId>e5563039-904c-459b-8e4a-61a2ff911534</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='newUserLanguage']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#newUserLanguage</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>056263df-c342-4d50-aca2-25dc971506a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>e8888268-bec3-4a46-9caa-5630300cd1b1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>eMC tBJ dyH iFc sAJ pBj BG7 XiG YbY L4E Bvi iyn H_e pBj qJc TKt LJB xD4</value>
      <webElementGuid>148b3bbd-0c29-4af6-8599-a2e1c9007e5f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>newUserLanguage</value>
      <webElementGuid>825c7564-c719-4d14-a68f-8a7404f9c265</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>locale</value>
      <webElementGuid>da4c7ac4-e6c9-4e17-83bf-04bff0dcf456</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>AfrikaansBahasa IndonesiaBahasa MalaysiaČeštinaDanskDeutschEnglish (Australia)English (India)English (UK)English (US)Español (Américas)Español (Argentina)Español (España)Español (México)FrançaisHrvatskiItalianoMagyarNederlandsNorsk bokmålPolskiPortuguês (Brasil)Português (Europeu)RomânăSlovenčinaSuomiSvenskaTagalogTiếng ViệtTürkçeΕλληνικάБългарскиРусскийУкраїнськаעבריתالعربيةहिन्दीবাংলাతెలుగుภาษาไทย한국어日本語简体中文繁體中文</value>
      <webElementGuid>35e2fa15-f0c0-48fc-9875-33c57dd3ca5c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;newUserLanguage&quot;)</value>
      <webElementGuid>fcabd500-f29a-4bf5-92a3-14aec7fe5530</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='newUserLanguage']</value>
      <webElementGuid>3ea9c74b-33a0-40d9-9b52-a3ef856943d4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select</value>
      <webElementGuid>3fd8b538-f040-4070-aa1a-256fdfe3c60d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'newUserLanguage' and @name = 'locale' and (text() = 'AfrikaansBahasa IndonesiaBahasa MalaysiaČeštinaDanskDeutschEnglish (Australia)English (India)English (UK)English (US)Español (Américas)Español (Argentina)Español (España)Español (México)FrançaisHrvatskiItalianoMagyarNederlandsNorsk bokmålPolskiPortuguês (Brasil)Português (Europeu)RomânăSlovenčinaSuomiSvenskaTagalogTiếng ViệtTürkçeΕλληνικάБългарскиРусскийУкраїнськаעבריתالعربيةहिन्दीবাংলাతెలుగుภาษาไทย한국어日本語简体中文繁體中文' or . = 'AfrikaansBahasa IndonesiaBahasa MalaysiaČeštinaDanskDeutschEnglish (Australia)English (India)English (UK)English (US)Español (Américas)Español (Argentina)Español (España)Español (México)FrançaisHrvatskiItalianoMagyarNederlandsNorsk bokmålPolskiPortuguês (Brasil)Português (Europeu)RomânăSlovenčinaSuomiSvenskaTagalogTiếng ViệtTürkçeΕλληνικάБългарскиРусскийУкраїнськаעבריתالعربيةहिन्दीবাংলাతెలుగుภาษาไทย한국어日本語简体中文繁體中文')]</value>
      <webElementGuid>d2729e1d-ed39-4a3c-aca3-73c4b9fe9e68</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
