<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Keluar</name>
   <tag></tag>
   <elementGuidId>0d500a76-7b7a-43cb-bbfd-b565d71ad0cb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='HeaderAccountOptionsFlyout-item-11']/div/div/div/div/div/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.DUt.Jea._HI.hA-.jzS.wYR.zI7.iyn.Hsu > div.hs0.un8.C9i.TB_ > div.jzS.ujU.un8.C9i.kwA > div.xuA > div.KS5.hs0.un8.C9i.TB_ > span.tBJ.dyH.iFc.sAJ.O2T.zDA.IZT.H2s.CKL</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>682651c1-086d-4833-b0d1-e8817cc3822e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>tBJ dyH iFc sAJ O2T zDA IZT H2s CKL</value>
      <webElementGuid>0a2576f9-f956-41b5-b28c-57e7a4186f45</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Keluar</value>
      <webElementGuid>587b0af1-38ed-4948-80af-d3523fc4b74f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Keluar</value>
      <webElementGuid>182ee73b-8580-4b24-8f58-48989bf7cb11</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;HeaderAccountOptionsFlyout-item-11&quot;)/div[@class=&quot;DUt Jea _HI hA- jzS wYR zI7 iyn Hsu&quot;]/div[@class=&quot;hs0 un8 C9i TB_&quot;]/div[@class=&quot;jzS ujU un8 C9i kwA&quot;]/div[@class=&quot;xuA&quot;]/div[@class=&quot;KS5 hs0 un8 C9i TB_&quot;]/span[@class=&quot;tBJ dyH iFc sAJ O2T zDA IZT H2s CKL&quot;]</value>
      <webElementGuid>5e447fe7-7b52-4cf8-a031-eb7ffa4facc3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='HeaderAccountOptionsFlyout-item-11']/div/div/div/div/div/span</value>
      <webElementGuid>109f1ae8-1e93-4b3c-bbcc-9a1654fb5a8b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[10]/div/div/div/div/div/span</value>
      <webElementGuid>bce9de64-dcc9-45a8-ba8f-6e51ebdab146</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@title = 'Keluar' and (text() = 'Keluar' or . = 'Keluar')]</value>
      <webElementGuid>43eb0d05-ebc0-4148-af43-6ab17c164ac0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
